accounts/urls.py
"""
Define URL patterns for accounts
   path() build URLS paths, and map URL to views.
   include() enables default authentication URLs provided by Django (eg. login, logout)
"""
from django.urls import path, include 
from . import views  

app_name = 'accounts'   # distinguish urls.py of this app accounts from other apps
urlpatterns = [         # pages that can be reached from localhost/accounts
    
    
    # When Django reads URL login page request, localhost:8000/accounts/login, 
    # the word accounts tells Django to look in accounts/urls.py 
    # and login tells Django to send requests to Django's default login view

    # Include default auth urls, including login & logout
    path('', include('django.contrib.auth.urls')),  
    # Registration page
    path('register/', views.register, name="register"),

]

learning_logs/urls.py
"""Defines URL patterns for learning logs."""
from django.urls import path    # function to build URL paths and map URLs to views
from . import views             # view retrieves and process data, and renders a page

app_name = 'learning_logs'      # helps Django to distinguish this urls.py from files of the same name in other apps
urlpatterns = [                 # list of individual pages that can be requested from the learning_log apps
    # Home page
    path('', views.index, name='index'),# '': base URL (http://localhost:8000). route the request to a view
                                        # views.index: specifies which function to call
                                        # name = 'index': provides the name index for this URL
    # Page with list of topics
    path('topics/', views.topics, name='topics'),       # refer to this URL with the alias 'topics'
    # Page listing all entries of a topic
    path('topics/<int:topic_id>', views.topic, name='topic'), # topic_id is a reference to topic.id 
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for addiging a new entry
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),    # we need a topid_id argument to tell which topic is associated with the entry
    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),    # Include the urls.py from app accounts. Accept any request from http://localhost:8000/accounts/...
    path('', include('learning_logs.urls')),        # include the module learning_logs.urls
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):                                  # inherit from Model
    """A topic the user is writing on"""
    text = models.CharField(max_length=200)                 # reserve 200 char in the db to hold names
    date_added = models.DateTimeField(auto_now_add=True)    # when user create a new topic, automatically add data and time

    
    def __str__(self):
        """Return a string representation of the model"""
        return self.text
    
class Entry(models.Model):
    """An entry for a topic"""
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)    # Topic is the foreign key; when a topic is deleted, all the entries associated with it should be deleted too.
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)            # present entries in the order they are created

    class Meta:
        verbose_name_plural = 'entries'                             # without this attribute, Django would refer to multiple entries as Entrys

    def __str__(self):
        """Return a short string representing the entry"""
        if len(self.text) < 80:
            return self.text
        return f"{self.text[:80]}..."

learning_logs/forms.py
from django import forms    # import the module to build forms

from .models import Topic, Entry   # import model you need

class TopicForm(forms.ModelForm):
    """Build a form automatically with ModelForm"""
    class Meta:
        model = Topic
        fields = ['text']       # include only text, not date
        labels = {'text': ''}   # blank label for text field

class EntryForm(forms.ModelForm):
    """Create a form associated with an entry of a topic"""
    class Meta:
        model = Entry           # based the class on Entry
        fields = ['text']       
        labels = {'text': ''}   # give a blank label to text
        widgets = {'text':forms.Textarea(attrs={'cols':80})}    # override  the default multiline text area with width of 80 columns instead of 40
        

learning_logs/views.py
from django.shortcuts import render, redirect   # import redirect(), to redirect user back to topics page after submitting the topic
from .models import Topic,  Entry           # import model associated with data we need
from .forms import TopicForm, EntryForm     # import the form for topic and entry


# Create your views here.
def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')  # render the response based on data provided by views

def topics(request):        # pass the URL request for the webpage
    """Show all available topics"""
    # try to change date_added
    topics = Topic.objects.order_by('date_added')   # QuerySet, a Django object similar to a list of objects that work in the db
    context = {'topics_key': topics}    # 'topics' = key to pass to the template topics.html
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):       # topic_id is a reference to topic.id. topic_id is passed by path, a function that maps URL paths and views 
    """Show a single topic and all its entries"""
    topic = Topic.objects.get(id=topic_id)     
    entries = topic.entry_set.order_by('-date_added')   # reverse lookup <modelname>_set and then order by date_added 
    context = {'topic_key': topic, 'entries_key': entries}
    return render(request, 'learning_logs/topic.html', context)
    
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        # No data submitted. Create a blank form
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid(): # check all required fields have been filled in, text < 200 characters, etc
            form.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form. Run only in these 2 circumstances
    context = {'form_key': form}
    return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request, topic_id):   # store the topic_id from the URL request
    """Add a new entry for a particular topic"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted. Create a blank form
        form = EntryForm()
    else:
        # POST data submitted; process data
        form = EntryForm(data=request.POST)  # make an instance populated with POST data from the request object
        if form.is_valid():                  # check all required fields have been filled
            new_entry = form.save(commit = False)  # do not save to db yet, but wait to add topic
            new_entry.topic = topic
            new_entry.save()                 # save entry to db
            return redirect('learning_logs:topic', topic_id = topic_id) # redirect to the view of all entries of the topic
    
    # Display a blank or invalid form in case info is missing
    context = {'topic_key': topic, 'form_key': form}
    return render(request, 'learning_logs/new_entry.html', context)

def edit_entry(request, entry_id):
    """Edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)  # get the entry object that user wants to edit
    topic = entry.topic                     # get the topic

    if request.method != 'POST':
        # Initial request: return pre-fill form with current entry'
        form = EntryForm(instance=entry)    # create the form with the info of the pre-existing entry object
    else:
        # POST changed data submitted; process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()     # no need to add arguments, because entry is already associated with topic
            return redirect('learning_logs:topic', topic_id = topic.id)

    context = {'entry_key': entry, 'topic_key': topic, 'form_key': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
<h1> 
  <a href="{% url 'learning_logs:index' %}">Learning Log</a> - 
  <a href="{% url 'learning_logs:topics' %}">Topics</a> - 
  
  {% comment %} Login + Register Form {% endcomment %}
  {% if user.is_authenticated %}
    Hello, {{ user.username }}.
  {% else %}
    <a href="{% url 'accounts:register' %}">Register</a>
    <a href="{% url 'accounts:login' %}">Log in</a>
  {% endif %}

  {% comment %} Logout Form {% endcomment %}
    {% comment %} the logout req uses POST, else attackers can force logout with http://localhost:8001/accounts/logout {% endcomment %}
    {% comment %} in case we used {% url 'accounts:logout' %} {% endcomment %}
  {% if user.is_authenticated %}
    <hr />              {% comment %} place request at the bottom, below horizontal rule {% endcomment %}
    <form action="{% url 'accounts:logout' %}" method = 'post'>
      {% csrf_token %}  {% comment %} prevent unauthorized access to db {% endcomment %}
      <button name='submit'>Logout</button>
    </form>
  {% endif %}
  
</h1>

{% block content %}{% endblock content%}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:topic' topic_key.id %}">{{topic_key}}</a>
  </p>  
  
  <p>Edit entry:</p>
  
  <form action="{% url 'learning_logs:edit_entry' entry_key.id %}" method='post'>  {% comment %} pass the entry_key.id so the edit_entry() function in views can change the correct entry object {% endcomment %}
    {% csrf_token %}
    {{form_key.as_div}}  
    <button name='submit'>Save changes</button>  
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
  <p>This Journal helps to keep track of topics of interest.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:topic' topic_key.id %}">{{topic_key}}</a>
  </p> 
 
  <p>Add a new entry:</p>

  <form action="{% url 'learning_logs:new_entry' topic_key.id %}" method="post">
    {% csrf_token %}
    {{ form_key.as_div }}
    <button name="submit">Add entry</button>
  </form>


{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:topics' %}">List of topics</a>
  </p>


  <p>Add a new topic:</p>
  
  <form action="{% url 'learning_logs:new_topic' %}" method='post'>     {% comment %} send data to the view function new_topic() {% endcomment %}
    {% csrf_token %}        {% comment %} prevent unauthorized access to the server {% endcomment %}
    {{ form_key.as_div }}   {% comment %} create all fields defined in forms.py. Render all form elements as HTML <div></div> for better display {% endcomment %}
    <button name="submit">Add topic</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topic: {{topic_key.text}}</p>
  <p>Entries:</p>
  <p>
    <a href="{% url 'learning_logs:new_entry' topic_key.id %}">Add a new entry</a>
  </p>
  <ul>
    {% for entry in entries_key %}
      <li>
        <p>{{entry.date_added | date:'M d, Y | H:i'}}</p>
        <p>{{entry.text | linebreaks }}</p>
        <p>
          <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>  {% comment %} This template tag redirect to edit_entry {% endcomment %}
        </p>  
      </li>  
    {% empty %}
      <li>There are no entries for this topic yet.</li>
    {% endfor %}
  </ul>


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topics</p>
<ul>
  {% for topic in topics_key %}   {% comment %} key dictionary 'topics' in views.py {% endcomment %}
    <li>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a>   {% comment%} topic.id retrives the ID of a topic {%endcomment%}
    </li> 
    {% empty %}
    <li>No topics have been added yet.</li>  
  {% endfor %}
</ul>

<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}